apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  ingressClassName: apisix
  http:
    - name: keycloak-all
      match:
        hosts:
          - "*"
        paths:
          - "/auth/*"
      backends:
        - serviceName: keycloak-keycloakx-http
          servicePort: 80
